FROM debian:bookworm
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libegl-dev \
    libgles2-mesa-dev \
    libgpiod-dev \
    libgbm-dev \
    libdrm-dev \
    pkg-config